### ISSUE TITLE
Update to TypeScript 5.5

### ISSUE THREAD

**Issue by Ewok167** [Prozi/detect-collisions#77] opened 2024-06-27 22:30 UTC
Hi. Unless I'm mistaken, using TypeScript 5.5 should allow importing the library properly. As described here: [Easier API Consumption from ECMAScript Modules](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#easier-api-consumption-from-ecmascript-modules).

Because I have the same issue as described in this PR: [microsoft/TypeScript#57133](https://www.github.com/microsoft/TypeScript/pull/57133) when using this library.

Some other dependencies, including RBush, have updates as well.

None of the updates should require any significant changes, if any.

**Comment by Prozi** [comment] 2024-07-14 23:29
will look into this ASAP thx @Ewok167

**Comment by Prozi** [comment] 2024-07-15 03:02
@Ewok167 done please test

**Comment by Prozi** [comment] 2024-07-15 03:02
check since v9.9.0

**Comment by Ewok167** [comment] 2024-07-15 19:47
> @Ewok167 done please test

Thanks. But it doesn't seem to have fixed my issue, hmm. Were you already aware of some problems with importing this lib?

I use esbuild to build for browser, I tried esm and cjs formats but the same thing happened. TS says the imports are good and there is no default import, however after build it is the vice-versa. I can do `import abc from "detect-collisions"` and abc is an object containing all the exports. I can't import anything specifically. Only this library has had issues with my esbuild setup, I will try to get a simple example to test.

**Comment by Prozi** [comment] 2024-07-17 22:18
@Ewok167 how do you import the library?

`import { System } from 'detect-collisions';`

should normally work

what error you get?

can you create a minimal example repository I can look at?

I'm reopening the issue since you say it's not done yet

mind you, the library is in typescript in src and the dist folder is compiled tsc compiled 5.5 into 

https://github.com/Prozi/detect-collisions/blob/master/tsconfig.json#L12

target: es2015

it should work totally in any environment node webpack rollup browser as module import whatever

**Comment by Prozi** [comment] 2024-07-17 22:22
@Ewok167  I have no clue why in your project

```
import { System } from 'detect-collisions'
```

doesn't work, maybe the problem is elsewhere in your code

-----

why?

https://github.com/Prozi/detect-collisions/blob/master/package.json#L5
https://github.com/Prozi/detect-collisions/blob/master/dist/index.js#L40
https://github.com/Prozi/detect-collisions/blob/master/dist/system.js#L181

that's why

**Comment by Prozi** [comment] 2024-07-19 16:52
closing as I cannot reproduce so I wont fix

and you @Ewok167 didnt provide any example repository

**Closed** 2024-07-19 16:52 UTC
