### ISSUE TITLE
v6.2.1 polygons not colliding properly

### ISSUE THREAD

**Issue by alderzhang** [Prozi/detect-collisions#30] opened 2022-07-29 02:22 UTC
call checkCollision(a, b)

a =
{
    "pos": {
        "x": -1310.5,
        "y": 1642.3125
    },
    "r": 2.625,
    "offset": {
        "x": 0,
        "y": 0
    },
    "padding": 0,
    "type": "Circle",
    "isStatic": false,
    "isTrigger": false,
    "minX": -1313.125,
    "minY": 1639.6875,
    "maxX": -1307.875,
    "maxY": 1644.9375
}

b =
{
    "pos": {
        "x": -1418.1795805137715,
        "y": 1675.84985018349
    },
    "angle": 0,
    "offset": {
        "x": 0,
        "y": 0
    },
    "calcPoints": [
        {
            "x": 1.8498501834898633,
            "y": 5.1795805137716044
        },
        {
            "x": 180.20901121103307,
            "y": -58.520119853208115
        },
        {
            "x": 176.50931084405337,
            "y": -68.87928088075132
        },
        {
            "x": -1.8498501834898633,
            "y": -5.1795805137716044
        }
    ],
    "edges": [
        {
            "x": 178.35916102754322,
            "y": -63.69970036697972
        },
        {
            "x": -3.699700366979698,
            "y": -10.359161027543209
        },
        {
            "x": -178.35916102754322,
            "y": 63.69970036697972
        },
        {
            "x": 3.6997003669797266,
            "y": 10.359161027543209
        }
    ],
    "normals": [
        {
            "x": -0.33633639699815626,
            "y": -0.9417419115948376
        },
        {
            "x": -0.9417419115948381,
            "y": 0.3363363969981547
        },
        {
            "x": 0.33633639699815626,
            "y": 0.9417419115948376
        },
        {
            "x": 0.9417419115948372,
            "y": -0.336336396998157
        }
    ],
    "points": [
        {
            "x": 1.8498501834898633,
            "y": 5.1795805137716044
        },
        {
            "x": 180.20901121103307,
            "y": -58.520119853208115
        },
        {
            "x": 176.50931084405337,
            "y": -68.87928088075132
        },
        {
            "x": -1.8498501834898633,
            "y": -5.1795805137716044
        }
    ],
    "padding": 0,
    "type": "Polygon",
    "isStatic": false,
    "isTrigger": false,
    "minX": -1420.0294306972614,
    "minY": 1606.9705693027386,
    "maxX": -1237.9705693027386,
    "maxY": 1681.0294306972614
}

v5.0.1 returns true
v6.2.1 returns false

@Prozi I think it may be caused by the following change:
resigned from using clockwise(points) on points array of polygon - I thought that was necessary for proper rbush working with polygons but I don't think so anymore, if you encounter any problems with polygons not colliding properly please report asap thank you

**Comment by Prozi** [comment] 2022-07-29 08:58
@alderzhang thank you for finding this.

can you provide the createPolygon() and createCircle() parameters so I can create a test for this?

**Comment by Prozi** [comment] 2022-07-30 00:16
@alderzhang nevermind about the parameters, I got them from your post :-)

I fixed this in v6.2.2 and added 2 tests for this, and made stress test use clockwise polygons (which fail if not reversed for rbush)

sorry for this regression in v6.2.1

**Comment by Prozi** [comment] 2022-07-30 00:17
> 
call checkCollision(a, b)

a =
{
"pos": {
"x": -1310.5,
"y": 1642.3125
},
"r": 2.625,
"offset": {
"x": 0,
"y": 0
},
"padding": 0,
"type": "Circle",
"isStatic": false,
"isTrigger": false,
"minX": -1313.125,
"minY": 1639.6875,
"maxX": -1307.875,
"maxY": 1644.9375
}

b =
{
"pos": {
"x": -1418.1795805137715,
"y": 1675.84985018349
},
"angle": 0,
"offset": {
"x": 0,
"y": 0
},
"calcPoints": [
{
"x": 1.8498501834898633,
"y": 5.1795805137716044
},
{
"x": 180.20901121103307,
"y": -58.520119853208115
},
{
"x": 176.50931084405337,
"y": -68.87928088075132
},
{
"x": -1.8498501834898633,
"y": -5.1795805137716044
}
],
"edges": [
{
"x": 178.35916102754322,
"y": -63.69970036697972
},
{
"x": -3.699700366979698,
"y": -10.359161027543209
},
{
"x": -178.35916102754322,
"y": 63.69970036697972
},
{
"x": 3.6997003669797266,
"y": 10.359161027543209
}
],
"normals": [
{
"x": -0.33633639699815626,
"y": -0.9417419115948376
},
{
"x": -0.9417419115948381,
"y": 0.3363363969981547
},
{
"x": 0.33633639699815626,
"y": 0.9417419115948376
},
{
"x": 0.9417419115948372,
"y": -0.336336396998157
}
],
"points": [
{
"x": 1.8498501834898633,
"y": 5.1795805137716044
},
{
"x": 180.20901121103307,
"y": -58.520119853208115
},
{
"x": 176.50931084405337,
"y": -68.87928088075132
},
{
"x": -1.8498501834898633,
"y": -5.1795805137716044
}
],
"padding": 0,
"type": "Polygon",
"isStatic": false,
"isTrigger": false,
"minX": -1420.0294306972614,
"minY": 1606.9705693027386,
"maxX": -1237.9705693027386,
"maxY": 1681.0294306972614
}

v5.0.1 returns true
v6.2.1 returns false

@Prozi I think it may be caused by the following change:
resigned from using clockwise(points) on points array of polygon - I thought that was necessary for proper rbush working with polygons but I don't think so anymore, if you encounter any problems with polygons not colliding properly please report asap thank you

I thought this was not necessary because in my stress test I was using only counter-clockwise polygons (which are ok for rbush) and I haven't noticed any wrong collisions.

thanks again for pointing this out

**Comment by Prozi** [comment] 2022-07-30 00:21
closing as fixed

**Closed by Prozi** 2022-07-30 00:21 UTC
